### ISSUE TITLE
Trying to collect more than 50 Redis

### ISSUE THREAD

**Issue by mjabrandao** [powdahound/redis-collectd-plugin#20] opened 2015-09-23 12:22 UTC
Hi,

I'm collecting stats in different Host / Port, and when I'm trying to get values for more than 50 Redis I get this error:

```
[2015-09-23 11:49:36] Initialization complete, entering read-loop.
[2015-09-23 11:49:37] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-23 11:49:37] read-function of plugin `python.redis_info' failed. Will suspend it for 20.000 seconds.
[2015-09-23 11:49:57] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-23 11:49:57] read-function of plugin `python.redis_info' failed. Will suspend it for 40.000 seconds.
```
In collectd.conf I have this:

```
        <Module redis_info>
                Host "172.1.1.1"
                Port 7000
                Instance "172.1.1.1-7000"
                Verbose false
                Redis_used_memory "bytes"
                Redis_used_memory_peak "bytes"
                Redis_used_memory_lua "bytes"
                Redis_mem_fragmentation_ratio "gauge"
                Redis_used_cpu_sys "gauge"
                Redis_used_cpu_user "gauge"
                Redis_total_connections_received "counter"
                Redis_total_commands_processed "counter"
                Redis_instantaneous_ops_per_sec "gauge"
                Redis_expired_keys "counter"
                Redis_evicted_keys "gauge"
                Redis_uptime_in_days "gauge"
                Redis_connected_clients "gauge"
                Redis_client_longest_output_list "gauge"
                Redis_connected_slaves "gauge"
                Redis_lru_clock "counter"
        </Module>
```

Can someone please help me?

Thanks,
Mario

**Comment by powdahound** [comment] 2015-09-23 15:58
That's an error from redis due to the maxclients setting:

```
# Set the max number of connected clients at the same time. By default
# this limit is set to 10000 clients, however if the Redis server is not
# able to configure the process file limit to allow for the specified limit
# the max number of allowed clients is set to the current file limit
# minus 32 (as Redis reserves a few file descriptors for internal uses).
#
# Once the limit is reached Redis will close all the new connections sending
# an error 'max number of clients reached'.
#
# maxclients 10000
```
(from http://download.redis.io/redis-stable/redis.conf)

This plugin should be closing the connection as soon as its done using it but perhaps there's an issue with that logic. Sorry to say that I don't have time to debug this now but would be happy to review any PRs sent over.

**Comment by mjabrandao** [comment] 2015-09-24 10:55
Hi,

The problem is really in maxclients from Redis. At this point I'm monitoring more than 100 Redis instances, but if 1 of them reaches de maxclients limit, this plugin stop collecting stats from all Redis.

As you can see below, the plugin stop collecting during +/- 10h because only 1 of the Redis reached the maxclients limit, while the others have low connections.

```
[2015-09-23 18:00:02] Initialization complete, entering read-loop.
[2015-09-23 22:36:32] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-23 22:36:32] read-function of plugin `python.redis_info' failed. Will suspend it for 20.000 seconds.
[2015-09-23 22:36:52] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-23 22:36:52] read-function of plugin `python.redis_info' failed. Will suspend it for 40.000 seconds.
[2015-09-23 22:37:32] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-23 22:37:32] read-function of plugin `python.redis_info' failed. Will suspend it for 80.000 seconds.
[2015-09-23 22:38:52] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-23 22:38:52] read-function of plugin `python.redis_info' failed. Will suspend it for 160.000 seconds.
[2015-09-23 22:41:32] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-23 22:41:32] read-function of plugin `python.redis_info' failed. Will suspend it for 320.000 seconds.
[2015-09-23 22:46:52] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-23 22:46:52] read-function of plugin `python.redis_info' failed. Will suspend it for 640.000 seconds.
[2015-09-23 22:57:32] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-23 22:57:32] read-function of plugin `python.redis_info' failed. Will suspend it for 1280.000 seconds.
[2015-09-23 23:18:52] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-23 23:18:52] read-function of plugin `python.redis_info' failed. Will suspend it for 2560.000 seconds.
[2015-09-24 00:01:32] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-24 00:01:32] read-function of plugin `python.redis_info' failed. Will suspend it for 5120.000 seconds.
[2015-09-24 01:26:52] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-24 01:26:52] read-function of plugin `python.redis_info' failed. Will suspend it for 10240.000 seconds.
[2015-09-24 04:17:32] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR max number of clients reached\r'
[2015-09-24 04:17:32] read-function of plugin `python.redis_info' failed. Will suspend it for 20480.000 seconds.
[2015-09-24 10:01:47] Exiting normally.
```

It appears that your plugin is closing the connections, this doesn't seem to be an issue, but the real issue is that the plugin should "ignore" the Redis Instances from that can't collect info. 

The other problem is that I need to restart collectd process in order to start collecting data again. Even after the Redis instances dropped the number of maxclients, this plugin didn't recover and didn't start sending info again.

When you have some time, please consider this 2 important issues.

Thanks,
Mario

**Comment by powdahound** [comment] 2015-09-24 20:42
Try that. :)

**Comment by mjabrandao** [comment] 2015-09-28 09:17
Hi,

Thanks for your time.

I tried this new version, but still have an issue. I'm monitoring 6 Redis ( 172.22.1.1, 172.22.1.2, 172.22.1.3, ... ), but if 1 goes down for some reason, or the ip is not available or doesn't exist, the plugin still doesn't collect data to the other 5 Redis.

[2015-09-28 08:59:01] Initialization complete, entering read-loop.
[2015-09-28 09:01:08] redis_info plugin: Error connecting to 172.22.1.1:7000 - error(110, 'Connection timed out')
[2015-09-28 09:01:08] redis plugin: No info received
[2015-09-28 09:03:15] redis_info plugin: Error connecting to 172.22.1.1:7110 - error(110, 'Connection timed out')
[2015-09-28 09:03:15] redis plugin: No info received
[2015-09-28 09:05:23] redis_info plugin: Error connecting to 172.22.1.1:7120 - error(110, 'Connection timed out')
[2015-09-28 09:05:23] redis plugin: No info received
[2015-09-28 09:07:30] redis_info plugin: Error connecting to 172.22.1.1:7130 - error(110, 'Connection timed out')
[2015-09-28 09:07:30] redis plugin: No info received

Thanks,
Mario

**Comment by powdahound** [comment] 2015-09-28 14:22
Are you sure that those instances are available at that time? That looks like a reasonable error to see if the instances or network was having trouble.

**Comment by mjabrandao** [comment] 2015-09-28 14:31
Hi,

Yes, the instance is not available. For instance, if you have an Auto Scaling, the instance 172.22.1.1 is unhealthy, so it is replaced by 172.22.2.1, but the plugin should still be able to continue monitoring ( 172.22.1.2, 172.22.1.3, ... ).

Thanks,
Mario

**Comment by powdahound** [comment] 2015-09-28 14:45
Sorry, I misunderstood your earlier comment.

It's tough to troubleshoot this without replicating the failure myself locally, which I don't have have time to do. From reading the code, it looks like a read failure on one instance should not stop the others from being read. Also, the "no info received" error message should have a host:port included in it since it really only refers to a single attempt to read from one instance.

In your case perhaps it is the time delay caused by the TCP timeout that is resulting in the "not monitoring" behavior? This timeout is different than the "ERR max number of clients reached" error you first reported.

Moving forward it'd be most helpful if you could add some debugging logs to your local copy of the plugin and see if you can get more info about its behavior at the time of these networking issues. Thanks!

**Comment by mjabrandao** [comment] 2015-09-29 16:14
Hi,

After some more detailed testing, I realised everything is working fine!

Thanks,
Mario

**Comment by powdahound** [comment] 2015-09-29 17:27
Great to hear! Will close this now. :)

**Closed** 2015-09-29 17:28 UTC
